# Generated by Django 3.1.7 on 2021-03-31 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonaEP',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplicacion_1.persona')),
                ('escolaridad_completa', models.BooleanField(default=False)),
                ('fecha_nacimiento', models.DateField()),
                ('maxima_escolaridad_alcanzada', models.CharField(choices=[('SIN_ESCOLARIDAD', 'Sin Escolaridad'), ('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario'), ('TERCIARIO', 'Terciario'), ('UNIVERSITARIO', 'Universitario')], default='SIN_ESCOLARIDAD', max_length=16)),
                ('tiene_acompaniante', models.BooleanField(default=False)),
                ('tiene_cuidador', models.BooleanField(default=False)),
                ('vive_solo', models.BooleanField(default=False)),
                ('referente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiene_referente', to='aplicacion_1.persona')),
            ],
            bases=('aplicacion_1.persona',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
                ('persona_ep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicacion_1.personaep')),
            ],
        ),
    ]
